# Generated by Django 4.1 on 2022-09-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_collection_nft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date first observed')),
                ('malfunction', models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='1', max_length=1)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nft')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
