# Generated by Django 4.1 on 2022-09-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='malfunction',
            new_name='rating',
        ),
    ]
